module.exports = {
    Goal: "Goals",
    totalDistance: "Total Distance",
    opponentGoal: "Goals Conceded",
    ballPossession: "Ball Possession",
    OnTarget: "Shots On Target",
    ShotInsidetheArea: "Goals From The Box",
    ShotOutsidetheArea: "Goals Outside of The Box",
    Header: "Goals Scored with the head",
    passes: "Passes",
    accuratePasses: "Accurate Passes",
    keyPasses: "Key Passes",
    tackles: "Tackles",
    tacklesSuccess: "Tackles Success",
    TeamStats: "Team Statistics",
    TeamExtStats: "Extended Team Statistics",
    PlayerStats: "Player Statistics",
    GoalRegular: "Goals",
    Assist: "Assists",
    totalMinutesPlayed: "Total Minutes Played",
    AttemptonGoal: "Attempts on Goal",
    OnTarget: "Attempts on Target",
    topSpeed: "Top Speed",
    sprints: "Sprints",
    steals: "Steals",
    lostBall: "Lost Balls",
    foul: "Fouls",
    position: "Position",
    shirtNumber: "Shirt Number",
}