module.exports = {
    Goal: "שערי זכות",
    totalDistance: "מרחק כולל",
    opponentGoal: "שערי חובה",
    ballPossession: "החזקת כדור",
    OnTarget: "שערים למסגרת",
    ShotInsidetheArea: "שערים שנכבשו מתוך הרחבה",
    ShotOutsidetheArea: "שערים שנכבשו מחוץ לרחבה",
    Header: "שערים שנכבשו בנגיחה",
    passes: "מסירות",
    accuratePasses: "מסירות מדויקות",
    keyPasses: "מסירות מפתח",
    tackles: "תיקולים",
    tacklesSuccess: "תיקולים מוצלחים",
    TeamStats: "סטטיסטיקה קבוצתית",
    TeamExtStats: "סטטיסטיקה קבוצתית מורחבת",
    PlayerStats: "סטטיסטיקת שחקן",
    GoalRegular: "שערים",
    Assist: "בישולים",
    totalMinutesPlayed: "מספר דקות ששיחק",
    AttemptonGoal: "בעיטות לשער",
    OnTarget: "בעיטות למסגרת",
    topSpeed: "מהירות מירבית",
    sprints: "ספרינטים",
    steals: "חטיפות",
    lostBall: "איבודי כדור",
    foul: "עבירות",
    position: "עמדה",
    shirtNumber: "מספר חולצה",
}